# Usage Notes:
# 1. Create an empty directory named 'postgres-data' and 'pgadmin-data'.
# 2. When registering a server in pgAdmin, use 'db' as the hostname.

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: brasa-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin-data:/root/.pgadmin
    depends_on:
      - db

